name: "deploy-bicep-rg - Deploy Resource Group with Bicep"

on: 
  push:
    paths:
      - .github/workflows/deploy-bicep-rg.yml
      - bicep/resource-group.bicep

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    environment: Production
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@main

        # Log into Azure
      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        # Deploy Bicep file
      - name: deploy
        uses: azure/arm-deploy@v1
        with:
          scope: subscription
          region: uksouth
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          template: ./bicep/resource-group.bicep
          failOnStdErr: false
