name: "Terraform Plan/Apply"

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/test001-ukw-tf-plan-apply.yml
      - terraform/test001/*.tf*

#Special permissions required for OIDC authentication
permissions:
  contents: read
  id-token: write
  pull-requests: write

#These environment variables are used by the terraform azure provider to setup OIDC authenticate.
env:
  ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
  ARM_USE_AZUREAD: true

jobs:
  call-tf-plan-apply:
    uses: ./.github/workflows/tf-plan-apply.yml
    with:
      tfvars-file: test001
      location-abbreviated: ukw
    secrets: inherit
