name: test001 - hello world
on:
  push:
    paths:
      - .github/workflows/test001.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!